/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--color-canvas)',
        shell: 'var(--color-shell)',
        sheet: 'var(--color-sheet)',
        surface: 'var(--color-surface)',
        scrim: 'var(--color-scrim)',
        ink: 'var(--color-ink)',
        inverse: 'var(--color-inverse)',
        muted: 'var(--color-muted)',
        subtle: 'var(--color-subtle)',
        disabled: 'var(--color-disabled)',
        hairline: 'var(--color-hairline)',
        line: 'var(--color-line)',
        'line-light': 'var(--color-line-light)',
        control: 'var(--color-control)',
        'control-soft': 'var(--color-control-soft)',
        'control-quiet': 'var(--color-control-quiet)',
        'icon-button': 'var(--color-icon-button)',
        'small-button': 'var(--color-small-button)',
        'switch-on': 'var(--color-switch-on)',
        'switch-thumb': 'var(--color-switch-thumb)',
        'switch-off': 'var(--color-switch-off)',
        success: {
          soft: 'var(--color-success-soft)',
          strong: 'var(--color-success-strong)',
        },
        danger: {
          soft: 'var(--color-danger-soft)',
          strong: 'var(--color-danger-strong)',
        },
        empty: {
          soft: 'var(--color-empty-soft)',
          strong: 'var(--color-empty-strong)',
        },
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        hero: ['84px', { lineHeight: '1.02', letterSpacing: '0' }],
        greeting: ['28px', { lineHeight: '1', letterSpacing: '0' }],
        sheetTitle: ['20px', { lineHeight: '1', letterSpacing: '0' }],
        setting: ['28px', { lineHeight: '1', letterSpacing: '0' }],
        cardValue: ['20px', { lineHeight: '1', letterSpacing: '0' }],
        controlIcon: ['28px', { lineHeight: '1', letterSpacing: '0' }],
        section: ['20px', { lineHeight: '1.25', letterSpacing: '0' }],
        segment: ['18px', { lineHeight: '1', letterSpacing: '0' }],
        metric: ['20px', { lineHeight: '1', letterSpacing: '0' }],
        monthNav: ['16px', { lineHeight: '1', letterSpacing: '0' }],
        tileToday: ['14px', { lineHeight: '1', letterSpacing: '0' }],
        label: ['14px', { lineHeight: '1', letterSpacing: '0' }],
        body: ['16px', { lineHeight: '1.35', letterSpacing: '0' }],
        caption: ['12px', { lineHeight: '1', letterSpacing: '0' }],
        micro: ['10px', { lineHeight: '1', letterSpacing: '0' }],
      },
      spacing: {
        screen: '24px',
        sheet: '24px',
        action: '3.625rem',
        segment: '3.75rem',
        tile: '3.125rem',
        'icon-gap': '1.75rem',
        battery: '27px',
        'battery-h': '13px',
        'battery-nub-h': '5px',
        'battery-nub-w': '2px',
        'battery-nub-top': '3px',
        'battery-nub-offset': '-4px',
        'battery-inset': '2px',
        home: '36px',
      },
      borderRadius: {
        device: '44px',
        sheet: '32px',
        card: '20px',
        tile: '12px',
        control: '16px',
        controlInner: '12px',
        battery: '4px',
        batteryInner: '2px',
        pill: '999px',
      },
      boxShadow: {
        phone: 'none',
        control: 'none',
        thumb: 'none',
        softButton: 'var(--shadow-soft-button)',
      },
    },
  },
  plugins: [],
};
