/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        canvas: '#FBFCFC',
        shell: '#FBFCFC',
        sheet: '#FBFCFC',
        surface: '#FBFCFC',
        scrim: 'rgba(17, 17, 17, 0.42)',
        ink: '#111111',
        inverse: '#f7f7f4',
        muted: '#999999',
        subtle: '#999999',
        disabled: '#999999',
        hairline: '#F2F4F7',
        line: '#F2F4F7',
        'line-light': 'rgba(255, 255, 255, 0.52)',
        control: '#F5F6F7',
        'control-soft': '#ffffff',
        'control-quiet': '#E6E7EB',
        success: {
          soft: '#E9F5EE',
          strong: '#33B773',
        },
        danger: {
          soft: '#FAF0F0',
          strong: '#E44545',
        },
        empty: {
          soft: '#F5F6F7',
          strong: '#B9B9B9',
        },
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        hero: ['84px', { lineHeight: '1.02', letterSpacing: '0' }],
        greeting: ['28px', { lineHeight: '1', letterSpacing: '0' }],
        sheetTitle: ['20px', { lineHeight: '1', letterSpacing: '0' }],
        setting: ['28px', { lineHeight: '1', letterSpacing: '0' }],
        cardValue: ['20px', { lineHeight: '1', letterSpacing: '0' }],
        controlIcon: ['28px', { lineHeight: '1', letterSpacing: '0' }],
        section: ['20px', { lineHeight: '1.25', letterSpacing: '0' }],
        segment: ['18px', { lineHeight: '1', letterSpacing: '0' }],
        metric: ['20px', { lineHeight: '1', letterSpacing: '0' }],
        monthNav: ['16px', { lineHeight: '1', letterSpacing: '0' }],
        tileToday: ['14px', { lineHeight: '1', letterSpacing: '0' }],
        label: ['14px', { lineHeight: '1', letterSpacing: '0' }],
        body: ['16px', { lineHeight: '1.35', letterSpacing: '0' }],
        caption: ['12px', { lineHeight: '1', letterSpacing: '0' }],
        micro: ['10px', { lineHeight: '1', letterSpacing: '0' }],
      },
      spacing: {
        screen: '24px',
        sheet: '24px',
        action: '3.625rem',
        segment: '3.75rem',
        tile: '3.125rem',
        'icon-gap': '1.75rem',
        battery: '27px',
        'battery-h': '13px',
        'battery-nub-h': '5px',
        'battery-nub-w': '2px',
        'battery-nub-top': '3px',
        'battery-nub-offset': '-4px',
        'battery-inset': '2px',
        home: '36px',
      },
      borderRadius: {
        device: '44px',
        sheet: '32px',
        card: '20px',
        tile: '12px',
        control: '16px',
        controlInner: '12px',
        battery: '4px',
        batteryInner: '2px',
        pill: '999px',
      },
      boxShadow: {
        phone: 'none',
        control: 'none',
        thumb: 'none',
        softButton: '0 20px 48px rgba(17, 17, 17, 0.12)',
      },
    },
  },
  plugins: [],
};
